### ISSUE TITLE
can not run unit test in documentation

### ISSUE THREAD

**Issue by unit9a** [Wakanda/wakanda-digital-app-factory#4]
v2.0.0 release
Can not run unit test example in the documentation. http://doc.wakanda.org/home2.en.html#/Unit-Testing/Unit-Testing.100-1019075.en.html

Debugger response :: 
exception : C:/Program Files (x86)/Wakanda/Community/Server/Modules/unitTest/index.js at line 2

Test runner not defined, please call the init() method before running the test. index.js:284(anonymous function)

**Comment by hamzahik** [comment]
@unit9a please declare your Wakanda related issues at https://github.com/Wakanda/wakanda-issues/issues to get an answer asap
