### ISSUE TITLE
addRemoteStore throw error "The datastore's type "wakanda" is not available"

### ISSUE THREAD

**Issue by franak** [Wakanda/wakanda-digital-app-factory#6]
In Wakanda Enterprise 2.2.1 when i´d trying to connect to a remote 4D datastore, got and error:"The datastore's type "wakanda" is not available" The object pass to "addRemoteStore()" to get the remote datastore is:

{
hostname: "myserver:8050",
user: "myuser",
password: "mypassword",
ssl: false,
jsFile: "targetDS.js",
timeout: 15
}

**Comment by hamzahik** [comment]
@franak please declare your Wakanda related issues at https://github.com/Wakanda/wakanda-issues/issues to get an answer asap
